services:
  - type: web
    name: randa-care-pharmacy
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn randa.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: randa-db
          property: connectionString

databases:
  - name: randa-db
